services:
  agent_360_core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent_360_core
    image: agent_360_core:latest
    ports:
      - "3500:8000"
    networks:
      - agent_360
    restart: "on-failure"

networks:
  agent_360:
    name: agent_360-network
